#name: Build and Distribute
#
#on:
#  push:
#    paths:
#      - .github/workflows/ios.yml
#
#jobs:
#  build:
#    runs-on: macOS-latest
#    
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#      
#      - name: Install CocoaPods
#        run: |
#          gem install cocoapods
#          pod install
#          
#      - name: Archive
#        uses: actions-xcode/archive@v2
#        with:
#          project-scheme: 'CICDApp'
#          package: '.ipa'
#          
#      - name: Upload artifact
#        uses: actions/upload-artifact@v2
#        with:
#          name: 'CICDApp'
#          path: 'CICDApp.ipa'


name: Build and Distribute Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macOS-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install CocoaPods
        run: |
          gem install cocoapods
          pod install
          
      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: 'CICDApp'
          path: 'CICDApp.ipa'
          
      # Add a step to download the artifact
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: 'CICDApp'
          path: 'artifacts'
