name: Build and Distribute

on:
  push:
    paths:
      - .github/workflows/iOS_build.yml


jobs:
  build:
    runs-on: macOS-latest
    
    steps:
    
      - name: check Xcode version
        run: /usr/bin/xcodebuild -version
    
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install CocoaPods
        run: |
          gem install cocoapods
          pod install
          
      - name: Archive
        uses: actions-xcode/archive@v2
        with:
          project-scheme: 'CICDApp'
          package: '.ipa'
          
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: 'CICDApp'
          path: 'CICDApp.ipa'
